/**
 * Kamus bahasa Jawa (ngoko).
 *
 * Hanya teks antarmuka. Pesan dari server tetap tampil dalam bahasa Indonesia
 * — sama seperti teks yang belum ada di kamus mana pun — karena bahasa Jawa
 * di sini bahasa tambahan, bukan bahasa yang dijanjikan penuh.
 */
export const JV: Record<string, string> = {
  // navigasi
  Beranda: "Ngarep",
  Pemantauan: "Ngawasi",
  Pekerjaan: "Pagawéan",
  Catatan: "Cathetan",
  Pemicu: "Pamicu",
  Proses: "Proses",
  Paket: "Pakèt",
  Antrean: "Antrèan",
  Aset: "Asèt",
  Robot: "Robot",
  Mesin: "Mesin",
  Lingkungan: "Lingkungan",
  Penyewa: "Panyéwa",
  Pengguna: "Pangguna",
  Peran: "Peran",
  Lisensi: "Lisènsi",
  Setelan: "Setelan",

  // bentuk tunggal untuk judul kolom dan isian
  "Robot|satu": "Robot",
  "Proses|satu": "Proses",
  "Mesin|satu": "Mesin",
  "Lingkungan|satu": "Lingkungan",
  "Paket|satu": "Pakèt",

  // bilah atas
  "Cari proses, robot, antrean...": "Golèk proses, robot, antrèan...",

  // dasbor
  "Sedang Berjalan": "Lagi mlaku",
  "Pemicu Berikutnya": "Pamicu sabanjuré",
  "Peringatan Terbaru": "Pènget anyar",
  "Ringkasan Antrean": "Ringkesan antrèan",
  "Tidak bisa mengambil data dasbor.": "Ora bisa njupuk data dasbor.",
  Harian: "Saben dina",
  Mingguan: "Saben minggu",
  Bulanan: "Saben sasi",
  Tahunan: "Saben taun",
  "Rentang waktu: {0}": "Rentang wektu: {0}",
  "Hari ini": "Dina iki",
  "Sejak {0}": "Wiwit {0}",
  "Belum ada peringatan.": "Durung ana pènget.",
  "Tidak ada peringatan pada tingkat ini.": "Ora ana pènget ing tingkat iki.",
  "tiap {0} menit": "saben {0} menit",

  // kolom
  Nama: "Jeneng",
  Status: "Kahanan",
  Keadaan: "Kahanan",
  Prioritas: "Prioritas",
  Sumber: "Sumber",
  Kemajuan: "Kemajuan",
  Dibuat: "Digawé",
  Dimulai: "Diwiwiti",
  Selesai: "Rampung",
  Keterangan: "Katrangan",
  Versi: "Vèrsi",
  Ukuran: "Ukuran",
  Diterbitkan: "Diterbitaké",
  Berkas: "Berkas",
  Tingkat: "Tingkat",
  Pesan: "Pesen",
  Waktu: "Wektu",
  Jadwal: "Jadwal",
  "Jalan Berikutnya": "Mlaku sabanjuré",
  "Jalan Terakhir": "Mlaku pungkasan",
  "Zona Waktu": "Zona wektu",
  Percobaan: "Nyoba",
  Rujukan: "Rujukan",
  Tipe: "Jinis",
  Denyut: "Denyut",
  Memori: "Mèmori",
  Nilai: "Isi",
  Diubah: "Diowahi",
  Baru: "Anyar",
  Diproses: "Diproses",
  Berhasil: "Kasil",
  Gagal: "Gagal",
  Total: "Gunggung",
  Isi: "Isi",
  Galat: "Kaluputan",
  Info: "Info",
  Diunggah: "Diunggah",
  Oleh: "Déning",
  Kode: "Kodhe",
  "Masuk terakhir": "Mlebu pungkasan",
  Produk: "Prodhuk",
  Terpakai: "Kanggo",
  "Berlaku sampai": "Laku nganti",
  Izin: "Idin",

  // tombol dan aksi
  Muat: "Muat manèh",
  "Muat ulang": "Muat manèh",
  Jalankan: "Lakokna",
  Hentikan: "Mandhegna",
  Hapus: "Busak",
  Simpan: "Simpen",
  Batal: "Batal",
  Tutup: "Tutup",
  Tambah: "Tambah",
  Sunting: "Sunting",
  Unduh: "Undhuh",
  Unggah: "Unggah",
  Cari: "Golèk",
  Detail: "Rincian",
  Nyalakan: "Uripna",
  Matikan: "Patènana",
  Keluar: "Metu",
  Masuk: "Mlebu",
  "Tandai semua dibaca": "Tandhani kabèh wis diwaca",
  Tampilkan: "Tampilaké",
  Sembunyikan: "Singidaké",

  // pesan umum
  "Belum ada data.": "Durung ana data.",
  "Memuat...": "Ngemot...",
  "Tidak ada yang cocok.": "Ora ana sing cocog.",
  "Yakin menghapus": "Busak",
  Halaman: "Kaca",
  dari: "saka",
  dipilih: "dipilih",
  baris: "baris",
  "Nama pengguna": "Jeneng pangguna",
  "Kata sandi": "Tembung sandi",
  Bahasa: "Basa",
  "Pilih semua di halaman ini": "Pilih kabèh ing kaca iki",
  "Pilih baris": "Pilih baris",
  "Terjadi kesalahan.": "Ana kaluputan.",
  "(kosong)": "(kosong)",

  // profil
  "Menu profil": "Menu profil",
  "Ubah profil": "Owahi profil",
  "Ubah kata sandi": "Owahi tembung sandi",
  "Nama tampilan": "Jeneng tampilan",
  Surel: "Email",
  "Belum ada surel": "Durung ana email",
  "Kosongkan untuk menghapus.": "Kosongna yèn arep dibusak.",
  "Nama pengguna dipakai untuk masuk dan hanya bisa diubah Administrator.":
    "Jeneng pangguna dienggo mlebu lan mung bisa diowahi Administrator.",
  "Kata sandi saat ini": "Tembung sandi saiki",
  "Kata sandi baru": "Tembung sandi anyar",
  "Ulangi kata sandi baru": "Baleni tembung sandi anyar",
  "Minimal 8 karakter.": "Paling sethithik 8 karakter.",
  "Nama tampilan wajib diisi.": "Jeneng tampilan kudu diisi.",
  "Semua isian wajib diisi.": "Kabèh isian kudu diisi.",
  "Kata sandi baru minimal 8 karakter.": "Tembung sandi anyar paling sethithik 8 karakter.",
  "Ulangan kata sandi baru tidak sama.": "Tembung sandi anyar sing dibaleni ora padha.",
  "Kata sandi baru harus berbeda dari yang lama.": "Tembung sandi anyar kudu béda karo sing lawas.",
  "Kata sandi berhasil diganti.": "Tembung sandi kasil diganti.",
  "Menyimpan...": "Nyimpen...",

  // masuk
  "Nama pengguna atau kata sandi salah.": "Jeneng pangguna utawa tembung sandi salah.",
  "Memeriksa...": "Mriksa...",

  // proses
  "Klik ganda pada barisnya untuk melihat riwayat jalan dan catatannya.":
    "Klik kaping pindho ing barisé kanggo ndeleng riwayat mlaku lan cathetané.",
  "Sedang berjalan ({0}). Bisa dijalankan lagi setelah selesai.":
    "Lagi mlaku ({0}). Bisa dilakokaké manèh sawisé rampung.",

  // paket
  "Versi Terbaru": "Vèrsi paling anyar",
  "Jumlah Versi": "Cacahé vèrsi",
  "Diterbitkan Oleh": "Diterbitaké déning",
  "Titik Masuk": "Titik mlebu",
  "Riwayat versi": "Riwayat vèrsi",
  Terbaru: "Paling anyar",
  "Satu baris per paket, dengan versi tertingginya. Klik ganda untuk melihat semua versinya.":
    "Siji baris saben pakèt, karo vèrsi paling dhuwuré. Klik kaping pindho kanggo ndeleng kabèh vèrsiné.",
  "Belum ada paket yang diterbitkan. Terbitkan dari Studio: tab Design → grup OpenOrchestrator → Terbitkan.":
    "Durung ana pakèt sing diterbitaké. Terbitaké saka Studio: tab Design → grup OpenOrchestrator → Terbitkan.",

  // aset
  "Tambah aset": "Tambah asèt",
  "Semua tipe": "Kabèh jinis",
  "Nilai yang dipakai bersama oleh banyak proses. Isi aset Secret dan kata sandi aset Credential tidak pernah tampil di daftar.":
    "Isi sing dienggo bebarengan déning akèh proses. Isi asèt Secret lan tembung sandi asèt Credential ora tau katon ing daftar.",
  "Kata sandi aset Credential tidak pernah dikirim ke layar ini — hanya robot yang memintanya lewat activity Get Credential yang menerimanya.":
    "Tembung sandi asèt Credential ora tau dikirim menyang layar iki — mung robot sing njaluk liwat activity Get Credential sing nampa.",
  "Disandikan sebelum disimpan, dan tidak pernah muncul di daftar.":
    "Disandèni sadurungé disimpen, lan ora tau katon ing daftar.",
  "Kosongkan kalau tidak ingin menggantinya.": "Kosongna yèn ora arep diganti.",
  "Tanpa kata sandi": "Tanpa tembung sandi",
  "Tampilkan kata sandi": "Tampilaké tembung sandi",
  "Sembunyikan kata sandi": "Singidaké tembung sandi",
  "Nama aset wajib diisi.": "Jeneng asèt kudu diisi.",

  // catatan
  "Ikuti otomatis": "Tut wuri otomatis",
  "Semua tingkat": "Kabèh tingkat",
  "Paling banyak 500 baris terbaru. Untuk catatan satu proses atau satu pekerjaan, buka detailnya dari halaman Proses atau Pekerjaan.":
    "Paling akèh 500 baris paling anyar. Kanggo cathetan siji proses utawa siji pagawéan, bukak rincian saka kaca Proses utawa Pagawéan.",

  // pekerjaan
  "Pilih prosesnya dulu.": "Pilih prosesé dhisik.",
  "Argumen masukan bukan JSON yang sah.": "Argumen input dudu JSON sing sah.",
  'Contoh: {"in_Nama":"Budi"}': 'Tuladha: {"in_Nama":"Budi"}',

  // pemicu
  "Tambah pemicu": "Tambah pamicu",
  "Nama pemicu wajib diisi.": "Jeneng pamicu kudu diisi.",
  "Selang waktu": "Selang wektu",
  "Ekspresi cron": "Ekspresi cron",
  "Lima ruas: menit jam tanggal bulan hari. Kalau tanggal DAN hari sama-sama diisi, cukup salah satu cocok.":
    "Lima ruas: menit jam tanggal sasi dina. Yèn tanggal LAN dina padha diisi, cukup salah siji sing cocog.",
  "Jalankan tiap (menit)": "Lakokna saben (menit)",
  "Jadwalnya dihitung menurut zona ini, bukan waktu server.":
    "Jadwalé diétung miturut zona iki, dudu wektu server.",
  "Tiap 15 menit": "Saben 15 menit",
  "Tiap jam, di menit ke-0": "Saben jam, ing menit 0",
  "Tiap hari pukul 07:00": "Saben dina jam 07:00",
  "Tiap hari kerja pukul 07:00": "Saben dina kerja jam 07:00",
  "Tiap tanggal 1 tengah malam": "Saben tanggal 1 tengah wengi",
  "Tiap Sabtu pukul 22:30": "Saben Setu jam 22:30",

  // antrean
  "Klik ganda pada barisnya untuk melihat butir-butirnya.":
    "Klik kaping pindho ing barisé kanggo ndeleng isiné.",
  "maks {0}": "maks {0}",

  // robot dan lingkungan
  "Robot mendaftarkan dirinya sendiri saat JakRunner berdenyut pertama kali; tidak perlu dibuat lebih dulu di sini.":
    "Robot ndhaftar dhéwé nalika JakRunner denyut sepisanan; ora perlu digawé dhisik ing kéné.",
  "Belum ada robot yang mendaftar.": "Durung ana robot sing ndhaftar.",
  "Tambah lingkungan": "Tambah lingkungan",
  "Nama lingkungan wajib diisi.": "Jeneng lingkungan kudu diisi.",

  // gudang
  "Berkas yang dipakai bersama oleh proses — masukan, keluaran, lampiran. Klik ganda untuk melihat isinya.":
    "Berkas sing dienggo bebarengan déning proses — input, output, lampiran. Klik kaping pindho kanggo ndeleng isiné.",
  "Berkasnya tidak bisa dibaca.": "Berkasé ora bisa diwaca.",

  // pengguna
  "Tambah pengguna": "Tambah pangguna",
  "Nama pengguna wajib diisi.": "Jeneng pangguna kudu diisi.",
  "Pengguna baru butuh kata sandi minimal 6 karakter.":
    "Pangguna anyar butuh tembung sandi paling sethithik 6 karakter.",
  "Minimal 6 karakter.": "Paling sethithik 6 karakter.",
  Aktif: "Aktif",

  // setelan
  Layanan: "Layanan",
  "Penyewa aktif": "Panyéwa saiki",
  "Basis data": "Basis data",
  "Zona tampilan": "Zona tampilan",
  "Waktu server": "Wektu server",
  "Robot dianggap putus setelah": "Robot dianggep pedhot sawisé",
  "Masa berlaku token": "Umur token",
  "{0} detik": "{0} detik",
  "{0} jam": "{0} jam",
  "Isi basis data": "Isi basis data",
  "tanpa batas": "tanpa wates",

  // keadaan kosong
  "Tidak ada pekerjaan yang sedang berjalan.": "Ora ana pagawéan sing mlaku.",
  "Tidak ada pemicu yang aktif.": "Ora ana pamicu sing urip.",

  // potongan yang dirangkai
  terdaftar: "kadhaftar",
  terputus: "pedhot",
  menunggu: "ngentèni",
  "pekerjaan hari ini": "pagawéan dina iki",
  berhasil: "kasil",
  gagal: "gagal",
  "CPU / Memori": "CPU / mèmori",
  "Semua keadaan": "Kabèh kahanan",
  "Semua proses": "Kabèh proses",

  // navigasi Tenant dan Folders
  Tenant: "Tenant",
  Folders: "Folder",
  Folder: "Folder",
  "Folder|tab": "Folder",
  Automations: "Otomatisasi",
  Queues: "Antrèan",
  Assets: "Asèt",
  "Ember Penyimpanan": "Ember panyimpenan",
  Peringatan: "Pènget",
  Audit: "Audit",
  "Menu utama": "Menu utama",
  Bagian: "Pérangan",
  "Lihat semua peringatan": "Deleng kabèh pènget",

  // bilah folder
  "Folder Saya": "Folderku",
  "Folder baru": "Folder anyar",
  "Cari folder...": "Golèk folder...",
  "Tutup cabang": "Tutup cabang",
  "Buka cabang": "Bukak cabang",
  "Anda tidak ditugaskan ke folder ini.": "Sampéyan ora ditugasaké ing folder iki.",
  "Folder pribadi: hanya Anda yang melihatnya.": "Folder pribadi: mung sampéyan sing bisa ndeleng.",
  "Daftar folder tidak bisa diambil.": "Dhaptar folder ora bisa dijupuk.",
  "Tidak ada folder yang cocok.": "Ora ana folder sing cocog.",
  "Anda belum ditugaskan ke folder bersama mana pun.": "Sampéyan durung ditugasaké ing folder bareng endi waé.",
  "Belum ada folder yang bisa dibuka": "Durung ana folder sing bisa dibukak",
  "Anda belum ditugaskan ke folder bersama mana pun. Minta Administrator menugaskan Anda, atau pakai Folder Saya.": "Sampéyan durung ditugasaké ing folder bareng endi waé. Jaluk Administrator nugasaké sampéyan, utawa nganggo Folderku.",
  "Buka Folder Saya": "Bukak Folderku",

  // dasbor
  Processes: "Proses",
  Triggers: "Pamicu",
  Users: "Pangguna",
  Machines: "Mesin",
  "{0} aktif": "{0} urip",
  "Robot: {0}": "Robot: {0}",
  "Jobs Pekerjaan": "Pagawéan",
  "Jobs History": "Riwayat pagawéan",
  "Pekerjaan per keadaan · {0}": "Pagawéan miturut kahanan · {0}",
  "Pekerjaan per proses · {0}": "Pagawéan miturut proses · {0}",
  pekerjaan: "pagawéan",
  "Belum ada pekerjaan pada rentang ini.": "Durung ana pagawéan ing rentang iki.",
  "Tingkat keberhasilan {0}% dari {1} pekerjaan yang selesai.": "Tingkat kasil {0}% saka {1} pagawéan sing rampung.",
  "Belum ada pekerjaan yang selesai pada rentang ini.": "Durung ana pagawéan sing rampung ing rentang iki.",
  "Lainnya ({0} proses)": "Liyané ({0} proses)",
  "Robot yang ditugaskan ke folder ini": "Robot sing ditugasaké ing folder iki",
  "Seluruh penyewa": "Kabèh panyéwa",
  "Belum ada antrean di folder ini.": "Durung ana antrèan ing folder iki.",
  "Belum ada robot yang ditugaskan ke folder ini.": "Durung ana robot sing ditugasaké ing folder iki.",

  // keadaan
  Menunggu: "Ngentèni",
  Berjalan: "Mlaku",
  Menghentikan: "Lagi mandheg",
  Dihentikan: "Dihentikaké",
  Tersedia: "Sumadhiya",
  Sibuk: "Sibuk",
  Terputus: "Pedhot",
  "Dicoba ulang": "Dicoba manèh",
  Nonaktif: "Mati",

  // proses
  "Tambah proses": "Tambah proses",
  "Ubah proses": "Owahi proses",
  "Cari proses...": "Golèk proses...",
  "Belum ada robot yang ditugaskan ke folder ini, jadi pekerjaan yang dijalankan di sini akan menunggu.": "Durung ana robot sing ditugasaké ing folder iki, dadi pagawéan sing dilakokaké ing kéné bakal ngentèni.",
  "Tugaskan robot": "Tugasaké robot",
  "Pindahkan proses \"{0}\"": "Pindhahaké proses \"{0}\"",
  "Pemicu dan riwayat pekerjaannya ikut pindah.": "Pamicu lan riwayat pagawéané mèlu pindhah.",
  "Pilih paketnya dulu.": "Pilih pakèté dhisik.",
  "Nama proses unik di dalam folder ini. Folder lain boleh punya proses bernama sama.": "Jeneng proses siji-sijiné ing folder iki. Folder liya kena duwé proses kanthi jeneng sing padha.",
  "Proses '{0}' sudah ada di folder ini.": "Proses '{0}' wis ana ing folder iki.",
  "Belum ada proses di folder ini. Terbitkan dari Studio — proses baru masuk ke folder Shared — atau tambahkan dari paket yang sudah ada.": "Durung ana proses ing folder iki. Terbitaké saka Studio — proses anyar mlebu folder Shared — utawa tambahaké saka pakèt sing wis ana.",
  Ubah: "Owahi",
  "Pindahkan ke folder lain": "Pindhahaké menyang folder liya",

  // pekerjaan dan pemicu
  "Belum ada pekerjaan di folder ini.": "Durung ana pagawéan ing folder iki.",
  "Belum ada robot yang ditugaskan ke folder ini; pekerjaannya akan menunggu.": "Durung ana robot sing ditugasaké ing folder iki; pagawéané bakal ngentèni.",
  "Kosongkan supaya robot mana pun di folder ini yang sedang bebas mengambilnya.": "Kosongaké supaya robot endi waé ing folder iki sing lagi longgar njupuk.",
  "Robot mana pun di folder ini": "Robot endi waé ing folder iki",
  "Belum ada pemicu di folder ini.": "Durung ana pamicu ing folder iki.",
  "Pemicu tinggal di folder prosesnya: memindah proses ke folder lain ikut memindah pemicunya.": "Pamicu manggon ing folder prosesé: mindhah proses menyang folder liya uga mindhah pamicuné.",

  // paket
  "Paket yang dipakai proses di folder ini.": "Pakèt sing dienggo proses ing folder iki.",
  "Lihat seluruh umpan paket": "Deleng kabèh umpan pakèt",
  "Belum ada paket yang dipakai proses di folder ini.": "Durung ana pakèt sing dienggo proses ing folder iki.",
  "Hapus {0} versi {1} dari umpan paket? Proses yang memakai versi ini tidak bisa dijalankan lagi.": "Busak {0} vèrsi {1} saka umpan pakèt? Proses sing nganggo vèrsi iki ora bisa dilakokaké manèh.",
  "Hapus versi ini": "Busak vèrsi iki",

  // pemantauan
  "Atur robot folder ini": "Atur robot folder iki",
  "Robot yang ditugaskan ke folder ini mengambil pekerjaannya. Robot baru masuk ke folder Shared saat pertama kali tersambung.": "Robot sing ditugasaké ing folder iki njupuk pagawéané. Robot anyar mlebu folder Shared nalika sepisanan nyambung.",
  "Belum ada catatan di folder ini.": "Durung ana cathetan ing folder iki.",

  // antrean
  "Tambah antrean": "Tambah antrèan",
  "Lihat butir": "Deleng butir",
  "Hapus antrean \"{0}\" beserta {1} butirnya?": "Busak antrèan \"{0}\" sak {1} butiré?",
  "Pindahkan antrean \"{0}\"": "Pindhahaké antrèan \"{0}\"",
  "Butir-butirnya ikut pindah bersama antreannya.": "Butir-butiré mèlu pindhah bareng antrèané.",
  "Jumlah percobaan ulang tidak boleh negatif.": "Cacahé coba manèh ora olèh negatif.",
  "Nama antrean unik untuk seluruh penyewa: robot memanggilnya lewat nama.": "Jeneng antrèan siji-sijiné kanggo kabèh panyéwa: robot nyeluk liwat jeneng.",
  "Percobaan ulang maksimal": "Coba manèh paling akèh",
  "Butir yang gagal dicoba lagi sebanyak ini sebelum dianggap gagal permanen.": "Butir sing gagal dicoba manèh samono akèhé sadurungé dianggep gagal tenan.",
  "Terima rujukan kembar": "Tampa rujukan kembar",

  // aset
  "Belum ada aset di folder ini.": "Durung ana asèt ing folder iki.",
  "Pindahkan aset \"{0}\"": "Pindhahaké asèt \"{0}\"",
  "Robot tetap membacanya lewat nama yang sama.": "Robot tetep maca liwat jeneng sing padha.",

  // ember penyimpanan
  "Tambah ember": "Tambah ember",
  "Buka isinya": "Bukak isiné",
  "Hapus ember \"{0}\" beserta {1} berkasnya?": "Busak ember \"{0}\" sak {1} berkasé?",
  "Pindahkan ember \"{0}\"": "Pindhahaké ember \"{0}\"",
  "Berkas-berkasnya ikut pindah bersama embernya.": "Berkas-berkasé mèlu pindhah bareng emberé.",
  "Nama ember wajib diisi.": "Jeneng ember kudu diisi.",
  "Nama ember unik untuk seluruh penyewa: robot memanggilnya lewat nama.": "Jeneng ember siji-sijiné kanggo kabèh panyéwa: robot nyeluk liwat jeneng.",
  "Belum ada ember penyimpanan di folder ini.": "Durung ana ember panyimpenan ing folder iki.",
  "Ember ini masih kosong.": "Ember iki isih kosong.",

  // setelan folder
  Umum: "Umum",
  "Folder ini": "Folder iki",
  "Subfolder baru": "Subfolder anyar",
  Jenis: "Jinis",
  Jalur: "Dalan",
  "Tentang folder": "Bab folder",
  "Proses, pemicu, antrean, aset, dan ember penyimpanan tinggal di satu folder.": "Proses, pamicu, antrèan, asèt, lan ember panyimpenan manggon ing siji folder.",
  "Robot hanya mengambil pekerjaan dari folder tempat ia ditugaskan, kecuali pekerjaan yang menyebut namanya langsung.": "Robot mung njupuk pagawéan saka folder panggonané ditugasaké, kajaba pagawéan sing nyebut jenengé langsung.",
  "Hapus folder \"{0}\"? Folder harus sudah kosong; riwayat pekerjaannya pindah ke induknya.": "Busak folder \"{0}\"? Folderé kudu wis kosong; riwayat pagawéané pindhah menyang induké.",
  "Hapus folder": "Busak folder",
  "Pilih robot...": "Pilih robot...",
  "Lepas dari folder ini": "Copot saka folder iki",
  "Lepas robot \"{0}\" dari folder ini? Robot itu tidak akan mengambil pekerjaan folder ini lagi.": "Copot robot \"{0}\" saka folder iki? Robot kuwi ora bakal njupuk pagawéan folder iki manèh.",
  "Robot baru yang tersambung untuk pertama kali selalu masuk ke folder Shared. Subfolder baru mewarisi robot induknya saat dibuat.": "Robot anyar sing nyambung sepisanan mesthi mlebu folder Shared. Subfolder anyar nampa robot induké nalika digawé.",
  "Pilih pengguna...": "Pilih pangguna...",
  "Tugaskan pengguna": "Tugasaké pangguna",
  "Lepas \"{0}\" dari folder ini? Ia tidak akan melihat folder ini lagi.": "Copot \"{0}\" saka folder iki? Dhèwèké ora bakal ndeleng folder iki manèh.",
  "Administrator selalu bisa membuka semua folder bersama. Pengguna lain hanya melihat folder tempat ia ditugaskan.": "Administrator mesthi bisa mbukak kabèh folder bareng. Pangguna liyané mung ndeleng folder panggonané ditugasaké.",
  Ditugaskan: "Ditugasaké",
  "Belum ada robot yang ditugaskan ke folder ini. Pekerjaannya akan menunggu sampai ada.": "Durung ana robot sing ditugasaké ing folder iki. Pagawéané bakal ngentèni nganti ana.",
  "Belum ada pengguna yang ditugaskan ke folder ini.": "Durung ana pangguna sing ditugasaké ing folder iki.",
  "Folder bawaan": "Folder gawan",
  "Folder pribadi": "Folder pribadi",
  "Folder bersama": "Folder bareng",

  // dialog folder dan pindah
  "Nama folder wajib diisi.": "Jeneng folder kudu diisi.",
  "Nama folder tidak boleh memuat garis miring.": "Jeneng folder ora olèh ngemot garis miring.",
  "Sunting folder": "Owahi folder",
  Induk: "Induk",
  "Folder bawaan harus tetap di akar.": "Folder gawan kudu tetep ing oyot.",
  "Folder baru mewarisi pengguna dan robot induknya.": "Folder anyar nampa pangguna lan robot induké.",
  "(Akar — tanpa induk)": "(Oyot — tanpa induk)",
  "Pilih folder tujuannya dulu.": "Pilih folder tujuané dhisik.",
  Pindahkan: "Pindhahaké",
  "Folder tujuan": "Folder tujuan",
  "Tidak ada folder lain yang bisa Anda buka.": "Ora ana folder liya sing bisa sampéyan bukak.",

  // Tenant: folder
  "Folder bawaan tidak bisa dihapus.": "Folder gawan ora bisa dibusak.",
  "Masih punya subfolder.": "Isih nduwé subfolder.",
  "Masih berisi proses, pemicu, antrean, aset, atau ember.": "Isih isi proses, pamicu, antrèan, asèt, utawa ember.",
  bawaan: "gawan",
  "Buka folder ini": "Bukak folder iki",
  "Hapus folder \"{0}\"? Riwayat pekerjaannya pindah ke induknya.": "Busak folder \"{0}\"? Riwayat pagawéané pindhah menyang induké.",
  "Folder Saya milik pengguna": "Folderku duwèké pangguna",
  "Folder pribadi hanya terlihat oleh pemiliknya. Yang kosong ikut terhapus saat penggunanya dihapus.": "Folder pribadi mung katon kanggo sing nduwé. Sing kosong mèlu kebusak nalika pangguné dibusak.",
  "Hapus Folder Saya milik \"{0}\"?": "Busak Folderku duwèké \"{0}\"?",
  Pemilik: "Sing nduwé",
  "Belum ada yang membuka Folder Saya.": "Durung ana sing mbukak Folderku.",
  "Belum ada folder.": "Durung ana folder.",

  // Tenant: lainnya
  "Mesin ikut terdaftar sendiri saat robotnya pertama kali berdenyut.": "Mesin kadhaftar dhéwé nalika robote sepisanan ndenyut.",
  "Robot mendaftarkan dirinya sendiri saat JakRunner berdenyut pertama kali, dan langsung ditugaskan ke folder Shared.": "Robot ndhaftaraké awaké dhéwé nalika JakRunner sepisanan ndenyut, lan langsung ditugasaké ing folder Shared.",
  "Tidak di folder mana pun": "Ora ing folder endi waé",
  "Pengguna baru langsung ditugaskan ke folder Shared. Atur folder lainnya di Setelan setiap folder.": "Pangguna anyar langsung ditugasaké ing folder Shared. Atur folder liyané ing Setelan saben folder.",
  "Hanya yang belum dibaca": "Mung sing durung diwaca",
  "Tandai dibaca": "Tandhani wis diwaca",
  Komponen: "Komponèn",
  "Semua komponen": "Kabèh komponèn",
  "Cari pengguna atau sasaran...": "Golèk pangguna utawa sasaran...",
  "Yang tercatat hanya perubahan yang berhasil dilakukan orang — denyut, catatan, dan laporan robot tidak.": "Sing kacathet mung owah-owahan sing kasil ditindakaké wong — denyut, cathetan, lan laporan robot ora.",
  Aksi: "Tumindak",
  Sasaran: "Sasaran",
  Rincian: "Rincian",
  "Belum ada perubahan yang tercatat.": "Durung ana owah-owahan sing kacathet.",

  // audit: komponen dan aksi yang ditulis server
  Profil: "Profil",
  Sesi: "Sesi",
  Terbitkan: "Terbitaké",
  "Alihkan status": "Ganti kahanan",
  Buat: "Gawé",
  "Hapus butir": "Busak butir",
  "Unggah berkas": "Unggah berkas",
  "Hapus berkas": "Busak berkas",
  "Ganti kata sandi": "Ganti tembung sandhi",
  "Lepas pengguna": "Copot pangguna",
  "Lepas robot": "Copot robot",
  Bersihkan: "Resiki",

  // validasi di formulir
  "Nama proses wajib diisi.": "Jeneng proses kudu diisi.",
  "Nama antrean wajib diisi.": "Jeneng antrèan kudu diisi.",

  // tema
  Tampilan: "Tampilan",
  Terang: "Padhang",
  Gelap: "Peteng",
  "Ikuti sistem": "Manut sistem",

  // bilah penyewa dan penjaga halaman
  "Pengelolaan penyewa: folder, pengguna, robot, paket, peringatan, audit, setelan.": "Ngatur panyéwa: folder, pangguna, robot, pakèt, pènget, audit, setelan.",
  "Tidak ada akses": "Ora ana akses",
  "Peran Anda tidak mengizinkan membuka halaman ini. Minta Administrator menambahkan izinnya di Tenant › Pengguna › Peran.": "Peran sampéyan ora ngidini mbukak kaca iki. Jaluk Administrator nambahaké idiné ing Tenant › Pangguna › Peran.",
  "Peran Anda tidak mengizinkan membuka halaman ini.": "Peran sampéyan ora ngidini mbukak kaca iki.",

  // proses per folder
  "Nama proses dan pemicu cukup unik di dalam folder. Nama antrean, aset, dan ember tetap unik untuk seluruh penyewa, karena robot memanggilnya lewat nama.": "Jeneng proses lan pamicu cukup siji-sijiné ing njero folder. Jeneng antrèan, asèt, lan ember tetep siji-sijiné kanggo kabèh panyéwa, amarga robot nyeluk liwat jeneng.",

  // peran
  "Izin setiap peran diatur di tab Peran.": "Idin saben peran diatur ing tab Peran.",
  "Tambah peran": "Tambah peran",
  "Ubah peran": "Owahi peran",
  "Setiap pengguna memegang satu peran. Izinnya berlaku di semua folder tempat ia ditugaskan.": "Saben pangguna nyekel siji peran. Idiné ditrapaké ing kabèh folder panggonané ditugasaké.",
  Bawaan: "Gawan",
  "Semua izin": "Kabèh idin",
  "{0} dari {1} izin": "{0} saka {1} idin",
  "Lihat izin": "Deleng idin",
  "Peran Administrator tidak bisa dihapus.": "Peran Administrator ora bisa dibusak.",
  "Masih dipakai {0} pengguna. Ganti peran mereka dulu.": "Isih dienggo {0} pangguna. Ganti perané dhisik.",
  "Hapus peran \"{0}\"?": "Busak peran \"{0}\"?",
  "Akun robot (JakRunner) sebaiknya memakai peran Robot: izinnya persis yang dibutuhkan robot, tidak lebih.": "Akun robot (JakRunner) luwih becik nganggo peran Robot: idiné pas sing dibutuhaké robot, ora luwih.",
  "Nama peran wajib diisi.": "Jeneng peran kudu diisi.",
  "Peran bawaan dengan semua izin. Tidak bisa diubah atau dihapus, supaya selalu ada yang bisa mengurus OpenOrchestrator.": "Peran gawan kanthi kabèh idin. Ora bisa diowahi utawa dibusak, supaya tansah ana sing bisa ngurus OpenOrchestrator.",
  "Salin izin dari": "Salin idin saka",
  "Mulai dari izin peran lain, lalu ubah seperlunya.": "Miwiti saka idin peran liya, banjur owahi sak perluné.",
  "Semua: {0}": "Kabèh: {0}",
  Semua: "Kabèh",
  "{0} izin dipilih.": "{0} idin dipilih.",
  "Kotak yang mati adalah izin yang tidak dimiliki peran Anda sendiri.": "Kothak sing mati yaiku idin sing ora diduwèni peran sampéyan dhéwé.",
  "Peran Anda tidak punya izin ini.": "Peran sampéyan ora duwé idin iki.",
  Automasi: "Otomatisasi",
  "Pengelolaan penyewa": "Ngatur panyéwa",
  Lainnya: "Liyané",
  Lihat: "Deleng",
  "Ubah: menghentikan pekerjaan; robot memakainya untuk mengambil dan melaporkan pekerjaan.": "Owahi: mandhegaké pagawéan; robot nganggo iki kanggo njupuk lan nglaporaké pagawéan.",
  "Ubah: menambah dan memproses butir antrean.": "Owahi: nambah lan ngolah butir antrèan.",
  "Lihat: termasuk membuka isi aset rahasia dan kredensial.": "Deleng: kalebu mbukak isi asèt rahasia lan kredènsial.",
  "Ubah: denyut robot — akun JakRunner memerlukannya.": "Owahi: denyut robot — akun JakRunner mbutuhaké.",
  "Ubah: menugaskan orang dan robot, sekaligus melihat semua folder.": "Owahi: nugasaké wong lan robot, sekaligus ndeleng kabèh folder.",
  "Izin yang bisa diberikan hanya yang juga Anda miliki.": "Idin sing bisa diwènèhaké mung sing uga sampéyan duwèni.",

  // --- Robot Agent unattended ---
  "Tambah mesin": "Tambah mesin",
  "Mesin robot unattended butuh machine key untuk Robot Agent-nya. Mesin robot attended ikut terdaftar sendiri saat robotnya pertama kali berdenyut.": "Mesin robot unattended butuh machine key kanggo Robot Agent-é. Mesin robot attended kadhaftar dhéwé nalika roboté pisanan ndenyut.",
  "Robot Agent": "Robot Agent",
  "Online": "Online",
  "Offline": "Offline",
  "Slot": "Slot",
  "Job berjalan / slot": "Job sing mlaku / slot",
  "Machine key": "Machine key",
  "Belum ada": "Durung ana",
  "Robot unattended / semua robot di mesin ini": "Robot unattended / kabèh robot ing mesin iki",
  "Ganti machine key": "Ganti machine key",
  "Buat machine key": "Gawé machine key",
  "Kunci lama mesin \"{0}\" langsung berhenti berlaku, dan Robot Agent di sana harus diberi kunci baru. Lanjutkan?": "Kunci lawas mesin \"{0}\" langsung ora laku, lan Robot Agent ing kana kudu diwènèhi kunci anyar. Terusaké?",
  "Cabut machine key \"{0}\"? Robot Agent di mesin itu langsung berhenti bekerja.": "Cabut machine key \"{0}\"? Robot Agent ing mesin kuwi langsung mandheg nyambut gawé.",
  "Sebaiknya sama dengan nama komputer Windows-nya.": "Luwih becik padha karo jeneng komputer Windows-é.",
  "Ubah mesin": "Owahi mesin",
  "Cabut machine key": "Cabut machine key",
  "Job yang boleh berjalan bersamaan. Windows 10/11 hanya mengizinkan satu sesi; lebih dari satu butuh Windows Server dengan RDS.": "Job sing olèh mlaku bebarengan. Windows 10/11 mung ngidini siji sesi; luwih saka siji butuh Windows Server nganggo RDS.",
  "Lease penyiapan (detik)": "Lease persiapan (detik)",
  "Batas waktu menyiapkan sesi Windows tanpa kabar dari agent.": "Wates wektu nyiapaké sesi Windows tanpa kabar saka agent.",
  "Robot Agent {0} di {1}, terakhir masuk {2}.": "Robot Agent {0} ing {1}, pungkasan mlebu {2}.",
  "Sudah saya simpan": "Wis dak simpen",
  "Salin kunci ini sekarang dan masukkan saat memasang Robot Agent di mesin ini. Kunci ini tidak akan ditampilkan lagi.": "Salin kunci iki saiki lan lebokna nalika masang Robot Agent ing mesin iki. Kunci iki ora bakal ditampilaké manèh.",
  "Kunci yang hilang tidak bisa ditampilkan ulang — buat kunci baru, dan kunci lama langsung berhenti berlaku.": "Kunci sing ilang ora bisa ditampilaké manèh — gawé kunci anyar, lan kunci lawas langsung ora laku.",
  "Salin": "Salin",
  "Tersalin": "Wis disalin",
  "Tambah robot": "Tambah robot",
  "Ubah robot": "Owahi robot",
  "Robot unattended ditambahkan di sini dan diikat ke mesin Robot Agent-nya.": "Robot unattended ditambahaké ing kéné lan ditaleni menyang mesin Robot Agent-é.",
  "Perlu perhatian: {0}": "Perlu digatèkaké: {0}",
  "Sesi Windows": "Sesi Windows",
  "Belum ada kabar dari agent": "Durung ana kabar saka agent",
  "Siap": "Siap",
  "Belum siap": "Durung siap",
  "Pekerjaan|satu": "Pagawéan",
  "Nama robot wajib diisi.": "Jeneng robot kudu diisi.",
  "Tulis akun Windows sebagai DOMAIN\\nama, atau .\\nama untuk akun lokal.": "Tulisen akun Windows dadi DOMAIN\\jeneng, utawa .\\jeneng kanggo akun lokal.",
  "Robot Agent di mesin ini yang menjalankan job robot ini.": "Robot Agent ing mesin iki sing nglakokaké job robot iki.",
  "belum ada machine key": "durung ana machine key",
  "Akun Windows": "Akun Windows",
  "DOMAIN\\nama, atau .\\nama untuk akun lokal.": "DOMAIN\\jeneng, utawa .\\jeneng kanggo akun lokal.",
  "Sandi Windows": "Sandi Windows",
  "Sudah tersimpan. Biarkan kosong untuk tetap memakai yang lama.": "Wis kasimpen. Jarna kosong yèn tetep nganggo sing lawas.",
  "Sandi disimpan di mesin robot, bukan di Orchestrator": "Sandi disimpen ing mesin robot, dudu ing Orchestrator",
  "Orchestrator hanya menyimpan nama akunnya; sandinya diisi saat memasang Robot Agent.": "Orchestrator mung nyimpen jeneng akuné; sandiné diisi nalika masang Robot Agent.",
  "Sesudah job selesai": "Sawisé job rampung",
  "Logoff — tidak ada jendela sisa untuk job berikutnya": "Logoff — ora ana jendhéla turahan kanggo job sabanjuré",
  "Tetap login — untuk aplikasi yang harus terus terbuka": "Tetep login — kanggo aplikasi sing kudu tetep kabukak",
  "Diambil robot": "Dijupuk robot",
  "Menyiapkan sesi": "Nyiapaké sesi",
  "Hilang kontak": "Ilang kontak",
  "percobaan {0}": "jajalan {0}",
  "PID Executor": "PID Executor",
  "Batas waktu": "Wates wektu",
  "{0} menit": "{0} menit",
  "Tanpa batas": "Tanpa wates",
  "Kode galat": "Kode kasalahan",
  "Kegagalan ini disimpulkan Orchestrator karena robotnya tidak memberi kabar; laporan asli robot yang datang belakangan bisa menggantikannya.": "Gagal iki disimpulaké Orchestrator amarga robot ora ngabari; laporan asli robot sing teka mburi isih bisa ngganti.",
  "Percobaan ulang otomatis dari pekerjaan {0}.": "Jajalan ulang otomatis saka pagawéan {0}.",
  "Screenshot": "Screenshot",
  "Robot unattended": "Robot unattended",
  "Batas waktu (menit)": "Wates wektu (menit)",
  "Kosong = tanpa batas.": "Kosong = tanpa wates.",
  "Jeda berhenti (detik)": "Jeda mandheg (detik)",
  "Sebelum Executor dimatikan paksa.": "Sadurungé Executor dipatèni peksa.",
  "Percobaan ulang otomatis": "Jajalan ulang otomatis",
  "Hanya kalau gagal sebelum workflow berjalan.": "Mung yèn gagal sadurungé workflow mlaku.",
  "Tidak": "Ora",
  "Ambil akun Windows": "Njupuk akun Windows",

  // --- Start Job, aksi job, jeda, runtime mesin ---
  "Peran Anda tidak mengizinkan aksi ini.": "Peranmu ora ngidini tumindak iki.",
  "Sedang dihentikan. Pakai Matikan untuk menghentikannya paksa.": "Lagi dimandhegké. Nganggo Patèni kanggo mandhegké kanthi peksa.",
  "Pekerjaan ini sudah selesai.": "Pagawéan iki wis rampung.",
  "Batalkan sebelum diambil robot.": "Batalké sadurungé dijupuk robot.",
  "Minta robot menghentikan pekerjaan ini dengan rapi.": "Njaluk robot mandhegké pagawéan iki kanthi rapi.",
  "Matikan|job": "Patèni",
  "Belum diambil robot — belum ada proses yang perlu dimatikan.": "Durung dijupuk robot — durung ana proses sing kudu dipatèni.",
  "Hentikan paksa, tanpa menunggu robot berhenti dengan rapi.": "Mandhegké kanthi peksa, tanpa ngenteni robot mandheg kanthi rapi.",
  "Jeda": "Lèrèn",
  "Sudah dijeda atau sedang dijeda.": "Wis dilèrèni utawa lagi dilèrèni.",
  "Hanya pekerjaan yang sedang berjalan yang bisa dijeda.": "Mung pagawéan sing lagi mlaku sing isa dilèrèni.",
  "Tahan workflow sebelum activity berikutnya. Robot yang belum mendukung jeda mengabaikannya.": "Tahan workflow sadurungé activity sabanjuré. Robot sing durung ndhukung lèrèn ora nggatèkaké.",
  "Lanjutkan": "Terusaké",
  "Dijeda langsung di PC robot — lanjutkan dari sana.": "Dilèrèni langsung ing PC robot — terusaké saka kana.",
  "Pekerjaan yang sudah selesai tidak bisa dilanjutkan dari tengah. Pakai Jalankan Ulang.": "Pagawéan sing wis rampung ora isa diterusaké saka tengah. Nganggo Mlakokaké Manèh.",
  "Pekerjaan ini tidak sedang dijeda.": "Pagawéan iki ora lagi dilèrèni.",
  "Lanjutkan pekerjaan yang dijeda dari dasbor.": "Terusaké pagawéan sing dilèrèni saka dasbor.",
  "Jalankan Ulang": "Mlakokaké Manèh",
  "Pekerjaan ini belum berjalan.": "Pagawéan iki durung mlaku.",
  "Buat pekerjaan baru dengan konfigurasi yang sama. Pekerjaan ini tetap tercatat.": "Gawé pagawéan anyar kanthi konfigurasi sing padha. Pagawéan iki tetep kacathet.",
  "Buka Rekaman": "Bukak Rekaman",
  "{0} rekaman dari robot.": "{0} rekaman saka robot.",
  "Tidak ada rekaman untuk pekerjaan ini. Robot Agent menyimpan tangkapan layar saat pekerjaan gagal.": "Ora ana rekaman kanggo pagawéan iki. Robot Agent nyimpen gambar layar nalika pagawéan gagal.",
  "Lihat Log Job Ini": "Deleng Log Job Iki",
  "Lihat Semua Log Proses": "Deleng Kabèh Log Proses",
  "Aksi untuk {0}": "Tumindak kanggo {0}",
  "Matikan paksa pekerjaan ini?": "Patèni pagawéan iki kanthi peksa?",
  "Hentikan pekerjaan ini?": "Mandhegké pagawéan iki?",
  "Robot akan mematikan proses workflow SEKARANG, tanpa menunggu activity yang sedang berjalan selesai dan tanpa jeda berhenti rapi.": "Robot bakal matèni proses workflow SAIKI, tanpa ngenteni activity sing lagi mlaku rampung lan tanpa wektu mandheg rapi.",
  "Pekerjaan yang setengah jalan tidak dibereskan: berkas yang sedang ditulis bisa rusak, dan aplikasi yang dibuka workflow ditutup paksa. Pakai Hentikan kalau robot masih bisa berhenti dengan rapi.": "Pagawéan sing lagi setengah ora diresiki: berkas sing lagi ditulis isa rusak, lan aplikasi sing dibukak workflow ditutup peksa. Nganggo Mandhegké yèn robot isih isa mandheg kanthi rapi.",
  "Pekerjaan ini belum diambil robot, jadi langsung dibatalkan.": "Pagawéan iki durung dijupuk robot, dadi langsung dibatalké.",
  "Robot diminta berhenti dengan rapi pada denyut berikutnya. Kalau robotnya tidak berhenti, pakai Matikan.": "Robot dijaluk mandheg kanthi rapi ing denyut sabanjuré. Yèn roboté ora mandheg, nganggo Patèni.",
  "Klik ganda pada barisnya untuk melihat rincian dan catatannya.": "Klik kaping pindho ing barisé kanggo ndeleng rincian lan cathetané.",
  "Menunggu robot menjeda…": "Ngenteni robot nglèrèni…",
  "Menunggu robot melanjutkan…": "Ngenteni robot nerusaké…",
  "Dijeda di PC robot": "Dilèrèni ing PC robot",
  "Dimatikan paksa…": "Lagi dipatèni peksa…",
  "Dijeda": "Dilèrèni",
  "Permintaan berhenti dikirim ke robot.": "Panjaluk mandheg dikirim menyang robot.",
  "Permintaan mematikan paksa dikirim ke robot.": "Panjaluk matèni peksa dikirim menyang robot.",
  "Permintaan jeda dikirim ke robot.": "Panjaluk lèrèn dikirim menyang robot.",
  "Permintaan lanjut dikirim ke robot.": "Panjaluk nerusaké dikirim menyang robot.",
  "Job berhasil dijalankan ulang.": "Job kasil dimlakokaké manèh.",
  "Tipe runtime": "Jinis runtime",
  "Akun yang diminta": "Akun sing dijaluk",
  "Mana pun": "Endi waé",
  "Mesin yang diminta": "Mesin sing dijaluk",
  "Lama dijeda": "Suwéné dilèrèni",
  "Dijalankan ulang dari pekerjaan {0}.": "Dimlakokaké manèh saka pagawéan {0}.",
  "Rekaman": "Rekaman",
  "Runtime": "Runtime",
  "Input": "Input",
  "Output": "Output",
  "Diwarisi": "Diwarisi",
  "Rendah": "Asor",
  "Normal": "Normal",
  "Tinggi": "Dhuwur",
  "Prioritas job": "Prioritas job",
  "Dipakai job yang dijalankan dengan prioritas Diwarisi.": "Dienggo job sing dimlakokaké nganggo prioritas Diwarisi.",
  "Jalankan lagi — sedang {0}": "Mlakokaké manèh — lagi {0}",
  "Hapus saringan pekerjaan": "Busak saringan pagawéan",
  "Tanpa runtime": "Tanpa runtime",
  "Job Robot Agent berjalan / slot yang berlaku": "Job Robot Agent sing mlaku / slot sing laku",
  "{0} dari {1} slot terpakai": "{0} saka {1} slot kanggo",
  "Berapa job tiap tipe yang boleh berjalan bersamaan di mesin ini. Start Job hanya menawarkan tipe yang dimiliki mesin di folder itu. Windows 10/11 hanya mengizinkan satu sesi; lebih dari satu butuh Windows Server dengan RDS.": "Pira job saben jinis sing olèh mlaku bebarengan ing mesin iki. Start Job mung nawakaké jinis sing diduwèni mesin ing folder kuwi. Windows 10/11 mung ngidini siji sesi; luwih saka siji butuh Windows Server nganggo RDS.",
  "Jumlah runtime harus bilangan bulat 0 sampai 50.": "Cacahé runtime kudu wilangan wutuh 0 nganti 50.",
  "Nama mesin wajib diisi.": "Jeneng mesin kudu diisi.",
  "Memproses...": "Lagi diproses...",
  "{0} job berhasil dijalankan.": "{0} job kasil dimlakokaké.",
  "Job berhasil dijalankan.": "Job kasil dimlakokaké.",
  "Jumlah jalan wajib diisi.": "Cacahé mlaku kudu diisi.",
  "Isi bilangan bulat, tanpa koma atau tanda minus.": "Isi wilangan wutuh, tanpa koma utawa tandha minus.",
  "Paling sedikit 1 kali.": "Paling sethithik 1 kali.",
  "Paling banyak {0} kali.": "Paling akèh {0} kali.",
  "Tidak ada runtime yang tersedia. Untuk menjalankan job, daftarkan mesin ke folder ini dan pastikan mesinnya punya runtime.": "Ora ana runtime sing cumepak. Kanggo mlakokaké job, daftaraké mesin menyang folder iki lan priksa mesiné nduwé runtime.",
  "Anda": "Kowé",
  "Jalankan job": "Mlakokaké job",
  "Remah roti": "Remah roti",
  "Menjalankan...": "Lagi mlakokaké...",
  "Mulai": "Wiwit",
  "Pengaturan eksekusi": "Setélan eksekusi",
  "Di mesin mana, sebagai akun siapa, berapa kali, dan dengan prioritas apa proses ini dijalankan.": "Ing mesin endi, minangka akun sapa, kaping pira, lan nganggo prioritas apa proses iki dimlakokaké.",
  "Runtime & alokasi": "Runtime & alokasi",
  "Tidak ada runtime yang tersedia": "Ora ana runtime sing cumepak",
  "Atur runtime mesin": "Atur runtime mesin",
  "Akun": "Akun",
  "Cari akun robot atau pengguna dengan robot unattended yang ditugaskan ke folder ini, atau jalankan otomasi sebagai diri sendiri.": "Goleki akun robot utawa pangguna sing duwé robot unattended ing folder iki, utawa mlakokaké otomasi minangka awakmu dhéwé.",
  "Tugaskan akun robot ke folder ini": "Tugasaké akun robot menyang folder iki",
  "Akun pengguna/robot mana pun": "Akun pangguna/robot endi waé",
  "Akun pengguna": "Akun pangguna",
  "Akun robot": "Akun robot",
  "Cari mesin atau templat mesin yang sudah dikonfigurasi.": "Goleki mesin utawa cithakan mesin sing wis diatur.",
  "Mesin mana pun": "Mesin endi waé",
  "Jalankan proses": "Mlakokaké proses",
  "kali": "kali",
  "Mengikuti prioritas proses: {0}.": "Manut prioritas proses: {0}.",
  "Argumen masukan": "Argumen mlebu",
  "Pilih robotnya dulu.": "Pilih robot dhisik.",
  "Tugaskan": "Tugasaké",
  "Anda tidak bisa mengatur robot folder ini. Minta pengelola folder menugaskannya.": "Kowé ora isa ngatur robot folder iki. Njaluka pangurus folder nugasaké.",
  "Robot yang ditugaskan ke folder ini bisa mengambil job prosesnya, selama mesinnya juga terdaftar di folder ini.": "Robot sing ditugasaké menyang folder iki isa njupuk job prosesé, anggeré mesiné uga kadaftar ing folder iki.",
  "Semua robot sudah ditugaskan ke folder ini.": "Kabèh robot wis ditugasaké menyang folder iki.",
  "Buat robot baru": "Gawé robot anyar",
  "Buka konfigurasi mesin ini": "Bukak konfigurasi mesin iki",
  "Buka konfigurasi mesin": "Bukak konfigurasi mesin",

  // kaca Cathetan: saringan, kolom, ekspor
  "15 menit terakhir": "15 menit pungkasan",
  "30 menit terakhir": "30 menit pungkasan",
  "1 jam terakhir": "1 jam pungkasan",
  "6 jam terakhir": "6 jam pungkasan",
  "12 jam terakhir": "12 jam pungkasan",
  "24 jam terakhir": "24 jam pungkasan",
  "7 hari terakhir": "7 dina pungkasan",
  "Kemarin": "Wingi",
  "Rentang khusus": "Rentang mligi",
  "Sampai {0}": "Nganti {0}",
  "Dari": "Saka",
  "Sampai": "Nganti",
  "Terapkan": "Trapaké",
  "Isi waktu awal, waktu akhir, atau keduanya.": "Isi wektu wiwitan, wektu pungkasan, utawa loro-loroné.",
  "Waktu awal harus sebelum waktu akhir.": "Wektu wiwitan kudu sadurungé wektu pungkasan.",
  "Belum ada nilai di catatan rentang ini.": "Durung ana isi ing cathetan rentang iki.",
  "Cari pesan...": "Goleki pesen...",
  "Cari...": "Goleki...",
  "Ekspor": "Ekspor",
  "Mengekspor...": "Ngekspor...",
  "Host Identity": "Host Identity",
  "Kolom": "Kolom",
  "Waktu dan Pesan selalu tampil.": "Wektu lan Pesen tansah katon.",
  "Saringan": "Saringan",
  "Kembalikan ke bawaan": "Balèkaké menyang gawan",
  "Reset saringan": "Reset saringan",
  "Tidak ada catatan yang cocok dengan saringan.": "Ora ana cathetan sing cocog karo saringan.",
  "Paling banyak {0} baris terbaru yang cocok dengan saringan. Ekspor mengunduh sampai 50.000 baris dengan saringan yang sama.": "Paling akèh {0} baris paling anyar sing cocog karo saringan. Ekspor ngundhuh nganti 50.000 baris kanthi saringan sing padha.",

  // Open Assistant: mlebu liwat dasbor; kaca Mesin
  "Agent mesin ini online, tapi belum ada robot unattended yang diikat ke mesin ini, jadi ia tidak akan mendapat job. Buat robot unattended dan pilih mesin ini.": "Agent mesin iki online, nanging durung ana robot unattended sing diikat menyang mesin iki, dadi ora bakal olèh job. Gawéa robot unattended lan pilih mesin iki.",
  "Belum ada Open Assistant yang tersambung.": "Durung ana Open Assistant sing kasambung.",
  "Belum ada robot": "Durung ana robot",
  "Buka Open Assistant": "Bukak Open Assistant",
  "Bukan {0}?": "Dudu {0}?",
  "Cabut": "Cabut",
  "Coba buka lagi": "Jajal bukak manèh",
  "Kalau peramban bertanya, pilih Buka. Sesudah Open Assistant tersambung, tab ini boleh ditutup.": "Yèn panjelajah takon, pilih Bukak. Sawisé Open Assistant kasambung, tab iki olèh ditutup.",
  "Masuk dengan akun lain": "Mlebu nganggo akun liya",
  "Membuka Open Assistant…": "Mbukak Open Assistant…",
  "Menyambungkan...": "Nyambungaké...",
  "Open Assistant di {0} akan tersambung ke Open Orchestrator sebagai {1}.": "Open Assistant ing {0} bakal kasambung menyang Open Orchestrator minangka {1}.",
  "Open Assistant menampilkan proses dan jadwal yang boleh Anda lihat.": "Open Assistant nampilaké proses lan jadwal sing olèh kokdeleng.",
  "Open Assistant tersambung": "Open Assistant sing kasambung",
  "Open Assistant tidak disambungkan. Tab ini boleh ditutup.": "Open Assistant ora disambungaké. Tab iki olèh ditutup.",
  "Open Assistant tidak terbuka?": "Open Assistant ora kebukak?",
  "Open Assistant yang masuk lewat dasbor atas nama Anda. Mencabut sambungan langsung menghentikannya; Open Assistant itu perlu disambungkan lagi.": "Open Assistant sing mlebu liwat dasbor atas jenengmu. Nyabut sambungan langsung mandhegaké; Open Assistant kuwi kudu disambungaké manèh.",
  "Open Assistant yang tersambung atas nama Anda ikut terputus dan perlu disambungkan lagi.": "Open Assistant sing kasambung atas jenengmu uga pedhot lan kudu disambungaké manèh.",
  "Peran Anda tidak boleh menjalankan robot (izin robots.update), jadi Open Assistant tidak bisa disambungkan atas nama Anda. Minta pengelola penyewa mengubah peran Anda.": "Peranmu ora olèh mlakokaké robot (idin robots.update), dadi Open Assistant ora isa disambungaké atas jenengmu. Njaluka pangurus penyewa ngganti peranmu.",
  "Putuskan Open Assistant di {0}? Ia perlu disambungkan lagi.": "Pedhotaké Open Assistant ing {0}? Kudu disambungaké manèh.",
  "Robot Agent terakhir masuk dari komputer bernama {0}, bukan {1}.": "Robot Agent pungkasan mlebu saka komputer jeneng {0}, dudu {1}.",
  "Robot attended Anda di komputer itu boleh mengambil dan menjalankan pekerjaan.": "Robot attended-mu ing komputer kuwi olèh njupuk lan mlakokaké pagawéan.",
  "Robot {0} · terakhir aktif {1}": "Robot {0} · pungkasan aktif {1}",
  "Sambungan bisa dicabut kapan saja dari menu profil › Open Assistant tersambung.": "Sambungan isa dicabut kapan waé saka menu profil › Open Assistant sing kasambung.",
  "Sambungan dibatalkan": "Sambungan dibatalaké",
  "Sambungkan Open Assistant?": "Sambungaké Open Assistant?",
  "Tautan ini tidak lengkap atau sudah diubah. Mulai lagi dari tombol Masuk lewat dasbor di Open Assistant.": "Tautan iki ora jangkep utawa wis diowahi. Wiwiti manèh saka tombol Mlebu liwat dasbor ing Open Assistant.",
  "Tautan sambungan tidak sah": "Tautan sambungan ora sah",
  "Tersambung sejak {0}": "Kasambung wiwit {0}",
  "komputer ini": "komputer iki",
  "komputer: {0}": "komputer: {0}",
  "tautan ini berlaku satu menit.": "tautan iki laku sak menit.",
  "Sambungkan": "Sambungaké",

  // Mesin per folder (V12)
  "Apakah Anda yakin ingin menghapus Machine {0} dari Folder {1}?": "Apa kowé yakin arep mbusak Machine {0} saka Folder {1}?",
  "Atur mesin folder": "Atur mesin folder",
  "Belum ada mesin yang terdaftar di folder ini. Job folder ini akan menunggu sampai ada.": "Durung ana mesin sing kadaftar ing folder iki. Job folder iki bakal ngenteni nganti ana.",
  "Buat mesin baru": "Gawé mesin anyar",
  "Cari mesin...": "Golèk mesin...",
  "Daftarkan mesin": "Daftaraké mesin",
  "Didaftarkan": "Didaftaraké",
  "Folder: {0}": "Folder: {0}",
  "Hanya mesin yang terdaftar di folder proses ini. Mesin yang tidak online tampil, tapi tidak bisa dipilih.": "Mung mesin sing kadaftar ing folder proses iki. Mesin sing ora online katon, nanging ora isa dipilih.",
  "Hanya pengelola folder yang bisa mengatur mesin folder ini.": "Mung pangurus folder sing isa ngatur mesin folder iki.",
  "Hapus dari Folder": "Busak saka Folder",
  "Hapus|dari folder": "Busak",
  "Machine berhasil dihapus dari Folder.": "Machine kasil dibusak saka Folder.",
  "Machine berhasil ditambahkan ke Folder.": "Machine kasil ditambahaké menyang Folder.",
  "Machine tidak akan dihapus dari sistem. Machine hanya tidak lagi tersedia pada Folder ini.": "Machine ora bakal dibusak saka sistem. Machine mung ora cumepak manèh ing Folder iki.",
  "Mesin baru selalu terdaftar di folder Shared. Subfolder baru mewarisi mesin induknya saat dibuat. Job yang sedang berjalan tidak dihentikan saat mesinnya dihapus dari folder.": "Mesin anyar mesthi kadaftar ing folder Shared. Subfolder anyar marisi mesin induké nalika digawé. Job sing lagi mlaku ora dimandhegaké nalika mesiné dibusak saka folder.",
  "Mesin dalam pemeliharaan atau nonaktif tidak mengambil job baru; job yang sedang berjalan dibiarkan selesai. Mesin nonaktif juga tidak bisa didaftarkan ke folder.": "Mesin sing lagi diopèni utawa dipatèni ora njupuk job anyar; job sing lagi mlaku diumbar nganti rampung. Mesin sing dipatèni uga ora isa didaftaraké menyang folder.",
  "Mesin ini belum terdaftar di folder ini; robot ini tidak mengambil job folder ini.": "Mesin iki durung kadaftar ing folder iki; robot iki ora njupuk job folder iki.",
  "Mesin yang tersedia": "Mesin sing cumepak",
  "Nama Host": "Jeneng host",
  "Nama Mesin": "Jeneng Mesin",
  "Pekerjaan folder ini hanya berjalan di mesin yang terdaftar di tab Mesin.": "Pagawéan folder iki mung mlaku ing mesin sing kadaftar ing tab Mesin.",
  "Pilih proses dulu untuk melihat mesin folder prosesnya.": "Pilih proses dhisik kanggo ndeleng mesin folder prosesé.",
  "Pilih semua ({0})": "Pilih kabèh ({0})",
  "Robot folder ini di mesin ini": "Robot folder iki ing mesin iki",
  "Status|mesin": "Status",
  "Tambah Mesin": "Tambah Mesin",
  "Tambah Mesin ke Folder": "Tambah Mesin menyang Folder",
  "Tambah {0} Mesin": "Tambah {0} Mesin",
  "Tidak ada mesin yang bisa ditambahkan. Di Folder Saya hanya bisa didaftarkan mesin tempat robot Anda sendiri bekerja.": "Ora ana mesin sing isa ditambahaké. Ing Folderku mung isa didaftaraké mesin panggonané robotmu dhéwé makarya.",
  "Tidak ada mesin yang bisa ditambahkan: semua mesin sudah terdaftar di folder ini atau dinonaktifkan.": "Ora ana mesin sing isa ditambahaké: kabèh mesin wis kadaftar ing folder iki utawa dipatèni.",
  "Tidak ada mesin yang cocok.": "Ora ana mesin sing cocog.",
  "{0} dan {1} lainnya": "{0} lan {1} liyané",
  "{0} robot folder ini": "{0} robot folder iki",
  "Pemeliharaan": "Pangopènan",
  "Keluarkan mesin": "Wetokaké mesin",

  // Resolusi robot, sibuk lokal, pemicu catatan (V13–V14)
  "0 = bawaan agent (1024x768). Hanya berlaku untuk robot yang sesinya dibuat agent (sandi Windows disimpan di Orchestrator). Sesi konsol/auto-logon memakai resolusi layar mesin.": "0 = bawaan agent (1024x768). Mung ditrapaké kanggo robot sing sesiné digawé agent (sandi Windows disimpen ing Orchestrator). Sesi konsol/auto-logon nganggo resolusi layar mesin.",
  "Automasi lokal": "Otomasi lokal",
  "Dijalankan di PC robot, di luar Orchestrator. Robot ini tidak diberi job sampai selesai.": "Mlaku ing PC robot, ing njaba Orchestrator. Robot iki ora diwènèhi job nganti rampung.",
  "Kedalaman warna": "Jero warna",
  "Lebar": "Ambané",
  "Pemicu|jalan": "Pemicu",
  "Resolusi layar (unattended)": "Resolusi layar (unattended)",
  "Resolusi layar: lebar dan tinggi diisi berpasangan, masing-masing 200 sampai 8192 — atau keduanya 0 untuk bawaan agent (1024x768).": "Resolusi layar: amba lan dhuwur diisi bebarengan, saben 200 nganti 8192 — utawa loro-loroné 0 kanggo bawaan agent (1024x768).",
  "Resolusi {0}": "Resolusi {0}",
  "Sandi robot ini disimpan di mesin robot, jadi sesinya bukan buatan agent dan resolusi ini tidak diterapkan.": "Sandi robot iki disimpen ing mesin robot, dadi sesiné dudu gawéan agent lan resolusi iki ora ditrapaké.",
  "Sibuk (lokal)": "Sibuk (lokal)",
  "sejak {0}": "wiwit {0}",
  "Job": "Job",
  "Manual": "Manual",
  "Jadwal lokal": "Jadwal lokal",
};
